name: Provision and Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Provision Infrastructure"
    runs-on: ubuntu-latest
    
    # Este step disponibiliza a saída do Terraform (IP) para o Job de deploy
    outputs:
      ec2_ip: ${{ steps.tf_outputs.outputs.ec2_public_ip }}
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        env:
          TF_VAR_public_key: ${{ secrets.TF_VAR_PUBLIC_KEY }}
        run: terraform apply -auto-approve
        
      - name: Obter Output do IP
        id: tf_outputs
        working-directory: terraform
        run: |
          EC2_IP=$(terraform output -raw ec2_public_ip)
          echo "ec2_public_ip=$EC2_IP" >> $GITHUB_OUTPUT

  deploy:
    name: "Deploy Application"
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Wait for EC2 to Boot
        run: sleep 60 # Espera 1 minuto para o Ubuntu e SSH iniciarem
        
      - name: Executar comandos via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ needs.terraform.outputs.ec2_ip }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navegar até a pasta do projeto (O user_data já criou no /home/ubuntu/)
            cd /home/ubuntu
            
            # Se a pasta não existir (repo privado/falha no user_data), clona
            if [ ! -d "vlibras-whatsapp" ]; then
              git clone https://github.com/neriidev/vlibras-whatsapp.git
            fi
            
            cd vlibras-whatsapp
            
            # Puxar código mais recente da branch main
            git pull origin main
            
            # Subir o banco de dados e Redis primeiro (se necessário)
            docker-compose up -d postgres redis
            
            # Aguardar o banco (garante que evolution tem banco)
            sleep 10
            
            # Recriar as imagens Docker e iniciar tudo
            docker-compose up -d --build
